---

- name: users | Create Influx users
  command: "{{ influxdb_influx_bin }} -database '{{ item.database }}' -execute \"CREATE USER {{ item.name }} WITH PASSWORD '{{ item.password }}'\""
  with_items: "{{ influxdb_users }}"
  changed_when: false
  
- name: users | Setup Influx privileges
  command: "{{ influxdb_influx_bin }} -execute 'GRANT {{ item.grant }} ON \"{{ item.database }}\" TO \"{{ item.name }}\"'"
  with_items: "{{ influxdb_users }}"
  changed_when: false
